# Pytorch Basics


## 1. Tensors

Everything in PyTorch is based on Tensor operations. A Tensor is a multi-dimensional matrix containing elements of a single data type.


### Initialization


In [46]:
# zeros
x = torch.zeros(2, 2)
print("zeros(2, 2):", x)

# ones
x = torch.ones(2, 2)
print("ones(2, 2):", x)

# random
x = torch.rand(2, 2)
print("rand(2, 2):", x)

# from data
x = torch.tensor([20.5, 17.5, 0.05])
print("from data:", x)

zeros(2, 2): tensor([[0., 0.],
        [0., 0.]])
ones(2, 2): tensor([[1., 1.],
        [1., 1.]])
rand(2, 2): tensor([[0.3879, 0.7858],
        [0.7555, 0.2765]])
from data: tensor([20.5000, 17.5000,  0.0500])


In [47]:
# size
print("size:", x.size())

# data type
print("dtype:", x.dtype)

# from data with data type
x = torch.tensor([1.7, 2.1, 3.5], dtype=torch.int64)
print("from data with data type:", x)
print("dtype:", x.dtype)

size: torch.Size([3])
dtype: torch.float32
from data with data type: tensor([1, 2, 3])
dtype: torch.int64


### Operations


In [48]:
# normal addition

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[4, 3], [2, 1]])
z = x + y
print("add:", z)

# alternative
# torch.add(x, y)

# in-place addition

x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[4, 3], [2, 1]])
y += x
print("in-place add:", y)

# alternative
# y.add_(x)

add: tensor([[5, 5],
        [5, 5]])
in-place add: tensor([[5, 5],
        [5, 5]])


In [49]:
x = torch.tensor([[4, 8], [16, 32]])
y = torch.tensor([[2, 2], [2, 2]])

z = x - y
print("sub:", z)

z = x * y
print("mul:", z)

z = x / y
print("div:", z)

sub: tensor([[ 2,  6],
        [14, 30]])
mul: tensor([[ 8, 16],
        [32, 64]])
div: tensor([[ 2.,  4.],
        [ 8., 16.]])


In [50]:
# slicing

x = torch.rand(3, 5)
print(x)

print("x[:, 0]", x[:, 0])  # all rows, column 0
print("x[1, :]", x[1, :])  # row 1, all columns
print("x[1, 1]", x[1, 1])  # element at 1, 1

# Get the actual value if only 1 element in your tensor
print("x[1,1].item()", x[1, 1].item())

tensor([[0.1876, 0.9638, 0.1817, 0.6573, 0.0923],
        [0.6746, 0.2436, 0.1498, 0.7393, 0.1502],
        [0.0330, 0.9622, 0.2336, 0.4310, 0.7919]])
x[:, 0] tensor([0.1876, 0.6746, 0.0330])
x[1, :] tensor([0.6746, 0.2436, 0.1498, 0.7393, 0.1502])
x[1, 1] tensor(0.2436)
x[1,1].item() 0.24363571405410767


In [51]:
# reshaping

# 4x4 tensor
x = torch.rand(4, 4)

# reshape to 1x16 tensor
y = x.view(16)

# reshape to 2x8 tensor (the size -1 is automatically inferred from other dimensions)
z = x.view(-1, 8)

print("x:", x)
print("y:", y)
print("z:", z)

print("x.size():", x.size())
print("y.size():", y.size())
print("z.size():", z.size())

x: tensor([[0.5934, 0.9917, 0.7668, 0.2881],
        [0.6624, 0.0939, 0.5877, 0.3982],
        [0.3501, 0.2492, 0.5113, 0.1447],
        [0.3133, 0.6870, 0.5214, 0.2382]])
y: tensor([0.5934, 0.9917, 0.7668, 0.2881, 0.6624, 0.0939, 0.5877, 0.3982, 0.3501,
        0.2492, 0.5113, 0.1447, 0.3133, 0.6870, 0.5214, 0.2382])
z: tensor([[0.5934, 0.9917, 0.7668, 0.2881, 0.6624, 0.0939, 0.5877, 0.3982],
        [0.3501, 0.2492, 0.5113, 0.1447, 0.3133, 0.6870, 0.5214, 0.2382]])
x.size(): torch.Size([4, 4])
y.size(): torch.Size([16])
z.size(): torch.Size([2, 8])


### NumPy


In [52]:
# convert tensor to numpy array

a = torch.ones(5)
print(a)
print(type(a))

b = a.numpy()
print(b)
print(type(b))

# !!! IMPORTANT !!!
# If the Tensor is on the CPU (not the GPU), both objects will share
# the same memory location, so changing one will also change the other.

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [53]:
# convert numpy to tensor array

import numpy as np

a = np.ones(5)
print(a)
print(type(a))

b = torch.from_numpy(a)
print(b)
print(type(b))

c = torch.tensor(a)
print(c)
print(type(c))

# !!! IMPORTANT !!!
# Both 'b' and 'c' are now PyTorch tensors, but 'b' shares the same underlying data with 'a'.
# Modifying 'a' will also affect 'b' due to the shared data.

a += 1
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### GPU Support

By default all tensors are created on the CPU. But we can also move them to the GPU (if it's available), or create them directly on the GPU.


In [60]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# move to device
x = torch.rand(2, 2).to(device)

# directly create on device
y = torch.rand(2, 2, device=device)

z = torch.rand(2, 2)
# move to GPU
z.to("cuda")
# move to CPU
z.to("cpu")

tensor([[0.4632, 0.1731],
        [0.2428, 0.2674]])